### PR TITLE
Implement BSD compatibility functions.

### PR DESCRIPTION
**Pull request by guilt**

### CODE REVIEW

**Comment by GitMensch** [comment]
Looks good to me and seems to solve #58.
@wmcbrine Do you see any reason to not merge it as-is?

**Comment by wmcbrine** [comment]
The ESCDELAY stuff is wrong. (There's no meaningful implementation of it possible for PDCurses, except perhaps with BG's VT; but this is wrong even for that.)

In general, I'd still kind of like to be convinced of the need for any of these (i.e., does anybody use them?), but I did notice that they've been added to ncurses, so yeah...

Trivially (but it bugs me), I don't want ".gitignore" in the tree. (I already have one here, of course -- with its first line being ".gitignore"). Perhaps I should add a note about that to IMPLEMNT.md.

Anyway, I can merge this and then revert those things. But I still want to look more closely at a few details first.

**Comment by wmcbrine** [comment]
So, on further review --

I once wrote that my compatibility goals for PDCurses were, in order: 1) X/Open, 2) older PDCurses, and 3) ncurses. [Net]BSD wasn't on that list, but I'm not ruling it out. I'm just going to look a little more skeptically at features that only come from that side. Some of these things *have* made it into ncurses -- `is_keypad()`, `is_leaveok()`, `is_pad()`, `keyok()`, `define_key()`, and `set_tabsize()` -- while `touchoverlap()`, `underscore/underend()` (and w...), `flushok()` and `fullname()` have not.

`fullname()` has several issues. The implementation here is ignoring the `name` parameter, which is supposed to be used (if not NULL) as an address to write the name to. Moreover, it ignores the `termbuf` parameter, which is supposed to (and is documented here to) specify a termcap entry, which PDCurses doesn't deal with at all. I suggest that this function doesn't really fit into the PDCurses framework, and should be omitted.

`keyok()` and `define_key()` are written here as non-functional stubs, which I've been trying to remove from PDCurses where I can. Further, the things these functions are meant to do are again kind of meaningless outside of a termcap / terminfo environment.

`flushok()` -- The implementation here turns out to be a duplicate of the existing `immedok()`, which is one thing. The description in NetBSD curses says "Turn on and off Fflush(stdout) after refresh for the given window," which is different from immedok(). But in fact, it appears that the flag toggled by this function in NetBSD is never otherwise referenced, so it does nothing.

More later...

**Comment by wmcbrine** [comment]
The macro implementation of `is_term_resized()` as a synonym for `is_termresized()` isn't quite right, since the former takes parameters (in its NetBSD and ncurses versions), and the latter doesn't. And NetBSD and ncurses both draw a distinction between `resizeterm()` and `resize_term()`. Also, these can all be implemented as real functions, and therefore should be -- see https://github.com/wmcbrine/PDCurses/commit/7f5298a7fa4bd34f914209d2f097c9be5001b864 .

Finally, trivially, but many of the functions have been inserted in a way that breaks up blocks that were otherwise in alphabetical order.

**Comment by GitMensch** [comment]
@wmcbrine Thank you for the in-depth review (you may want to consider doing this as a "review" - possible within the code and "in general" by clicking "Files changed", then either the "+" in a code line to comment on it or the "Review changes" button on the upper right corner).

The current question is: What is the direction given for this PR now? If I understood it correctly: create a new one with only X+Y but not A+B taking care for C - but what is A-C,X-Z?

**Comment by wmcbrine** [comment]
I'm accepting is_keypad(), is_leaveok(), is_pad() and set_tabsize() (but filing them under ncurses); also accepting touchoverlap(), underend(), underscore(), wunderend(), and wunderscore(), as modified. I'm deferring is_term_resized() and resizeterm(), and perhaps gettmode(), pending possible better implementations. And I'm rejecting define_key(), flushok(), fullname(), keyok(), and set_escdelay().

Rather than go back and forth with PRs, I've gone ahead and committed the changes.

**Comment by GitMensch** [comment]
Thank you for 610d0eda37fd3da9851fe396b2fce784cb7cba28, e449e65597faf81249c23a23dff53c2ee68945f0, 7c00f33999426568743420224d5e5fd84314e75a.

**Comment by GitMensch** [comment]
@guilt Do you want to give `is_term_resized()`, `resizeterm()`, and perhaps `gettmode()` another try, following the review from @wmcbrine above or do you consider this finished for now?

**Comment by GitMensch** [comment]
friendly ping @guilt concerning the three missing BSD functions

**Pull request closed without merging**
