### PR TITLE
New port for SDL2

### PR DESCRIPTION
**Pull request by rgson**
I've created a new port for SDL2.

The new port is heavily based on the existing SDL1 port. It has Laura Michaels' SDL2 patch applied, but also a fair amount of important fixes and additional changes on top.

Firstly, the SDL2 port is updated to work with the current version of PDCurses (this repository's `master` branch at the time of writing, i.e. commit dc1d35e).

Secondly, I have fixed various issues that remained after applying the SDL2 patch. Rendering, resizing and mouse wheel support was broken. Some SDL1 code also remained, making compilation fail whenever `WIDE=Y` was not used.

Thirdly, I fixed the broken text input and also introduced proper wide character input for `PDC_WIDE` builds. Even "regular" input was broken due to differences between SDL1 and 2, allowing only characters with dedicated keys on the US keyboard layout and upper-case letters to be entered, but no special characters (e.g. Shift-2 would produce 2, not @). Now input should work as expected and respect the current keyboard layout. Unicode input is also supported when compiled with `WIDE=Y`.

The decision to make SDL2 a stand-alone port was taken both to avoid an unmaintainable mess of nested `#ifdef`s (the versions differ in `PDC_WIDE` sections, too) and to comply with the "PDCurses Implementor's Guide". Hopefully it should aid the review process as the changes does not risk breaking existing code.

### CODE REVIEW

**Comment by techtonik** [comment]
> Thirdly, I fixed the broken text input and also introduced proper wide character input for PDC_WIDE builds. 

Is it something that could be reviewed and merged separately?

**Comment by rgson** [comment]
It's been a while since I worked on this, but as far as I remember, that problem only exists with SDL2 and not with SDL1. So unless I'm mistaken, merging it separately without the SDL2 support would be nonsensical. Anyway, commit 4f87bc99736df0cc3736fec9a12426952ffa0385 seems to cover it.

**Comment by timofonic** [comment]
@rgson @techtonik Any news about this? SDL2 support would be superb 👍

**Comment by rgson** [comment]
@timofonic As far as I'm concerned, my part in this is pretty much done. Now it's up to the maintainers whether it should be merged or not.

At the current rate it seems unlikely to make it into this repo. While that's unfortunate, I'm not overly surprised given the size of the pull request and my lack of history as a contributor to the project. However, the SDL2 support is still available through [my fork](https://github.com/rgson/PDCurses-SDL2) (which changes nothing else). An appropriately modified version was also accepted into [Bill Gray's fork](https://github.com/Bill-Gray/PDCurses) (which contains a bunch of additional changes). Depending on your needs, either may be helpful to you.

**Comment by xucaen** [comment]
UNSUBSCRIBE

On Aug 21, 2017 1:07 AM, "Timofonic" <notifications@github.com> wrote:

@rgson <https://github.com/rgson> @techtonik <https://github.com/techtonik>
Any news about this? SDL2 support would be superb 👍

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wmcbrine/PDCurses/pull/14#issuecomment-323647390>, or mute
the thread

**Pull request merged**
