### PR TITLE
Make KEY_SIZE and is_termresize work in win32

### PR DESCRIPTION
**Pull request by jackmott**
I know that this will need some refactoring, happy to do the work if you point me in the right direction. This does work. I imagine it maybe should be optional to enable this feature? If so, how would be the best way to set that option?   Adding resizeX and resizeY to the SCREEN struct seems kludgy as well, is there a better way to store the new console size after a resize event?

### CODE REVIEW

**Comment by Bill-Gray** [comment]
Hi John,

    Haven't had a chance to test this yet,  but it does look interesting.
It would be nice to have user resizable windows in Win32 console mode.
I may incorporate it in my PDCurses fork;  not much is happening with
"official" PDCurses.

    In the Win32a (Windows GUI) and X11 flavors,  resizeX and resizeY
are globals,  rather than in the SCREEN struct.  For Win32a,  they are
PDC_n_rows and PDC_n_cols;  for X11,  they are XCursesLINES and XCurseCOLS.
The SDL flavor stores the height and width in _pixels_ as globals
pdc_sheight and pdc_swidth.

    So I was going to suggest you do likewise.  Though now that I think
about it,  maybe putting them in the SCREEN structure,  and using those
same variables in all four user-resizable flavors (Win32a,  X11,  SDL,
and now Win32 console) has some appeal to me.  Maybe having resizeX/Y
in the SCREEN structure is a kludge,  but globals could be considered
still more kludgey in some circles.

    Now,  as to making user-resizability optional:  am I correct in
thinking that we could do that by saying:  "if a particular switch is
set to allow user-resizable windows,  the last parameter to the
SetConsoleMode calls ought to have the ENABLE_WINDOW_INPUT bit set;
otherwise,  not"?  I'm assuming that if the ENABLE_WINDOW_INPUT flag
bit isn't set,  then you just get a non-resizable window,  and you
never see a WINDOW_BUFFER_SIZE_EVENT,  and _process_window_event()
never gets called.  Is that true?

Thanks!            -- Bill

**Comment by jackmott** [comment]
Regarding your question about ENABLE_WINDOW_INPUT - yes, correct. If we just don't set that, _process_window_event() never gets called.  Also in ncurses in linux, "is_termresized()" is is_term_resized(int,int)  where you pass in a potential new size, and it returns true/false if that size would be a new size or not.  Might be worth changing that so you can build cross platform with no ifdefs.  I've changed it on my own fork to work the same. It works nicely in both windows and linux, I can resize and reflow text pretty smooth.

**Comment by jackmott** [comment]
So, playing with this some last night, I realized that it doesn't work properly. The buffer resize notifications only fire if the *buffer* resizes, not the window.  If you make the window smaller in the vertical direction, the buffer doesn't change, and you get no event. It isn't clear that windows can handle this properly.

**Comment by Evolution0** [comment]
@jackmott Have you looked at the `mode` command in Windows? Specifically `mode {cols}, {lines}` I've used it previously to resize the buffer based on how big the console window is, `get_maxyx()` obviously doesn't work as I'm assuming it relies on PDCurses acknowledging resizes and updating the `y` and `x`  so what I have used in Python is `os.get_terminal_size()` and called the `mode` command with the values returned which worked to resize the buffer when the window is resized.

You could possibly call the `mode` command when the window resizes triggering the buffer resize notification? Sorry if this is unhelpful :/

**Comment by Bill-Gray** [comment]
@Evolution0 - We're fine with programmatically resizing the window (i.e.,  the program says "I wanna have 92 columns and 31 lines").  Which is what `mode` would get us.  The issue is when you have a user-resizable Win32 console window.  As things stand,  the user can click on the window border and resize it.  But instead of that generating an appropriate message ("time to handle a window resize event",  essentially),  scroll bars are added if you've shrunk the window and it appears,  from the viewpoint of the program,  as if you're still in (usually) an 80x25 window.  (Expand the window,  and black space is added to the right and bottom borders.)

**Comment by Evolution0** [comment]
Yeah after some research it seems to be an issue with `conhost.exe` and the windows API :(

Would it be possible to listen for `WM_SIZE` (and `WM_SIZING`) and manually call `WriteConsoleInput` to insert an `INPUT_RECORD` into `lpBuffer`, specifically a `WINDOW_BUFFER_SIZE_EVENT` containing a `WINDOW_BUFFER_SIZE_RECORD` with the values of how big the new buffer should be based on the changed window size as well as fire off a `KEY_RESIZE` event for PDCurses to catch?

**Pull request closed without merging**
